name: Pull Request
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    name: Run Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@main
      - name: RSpec
        uses: ./.github/actions/ruby-tests
